### ISSUE TITLE
Allow Users to abort Phone Number Confirmation action

### ISSUE THREAD

**Issue by svenseeberg** [netzbegruenung/keycloak-mfa-plugins#103] opened 2024-07-25 09:18 UTC
If users enter a typo in their phone number, they cannot abort. When trying to log in in a new browser profile, they are always presented with the form to enter the SMS code that is sent to the wrong number.

In my opinion it should be okay to add a link that allows the user to abort the required action. This will simply force the user to enter the phone number again during the next login. In the best scenario, aborting the confirmation will directly lead again to the require MFA screen.

**Comment by melegiul** [comment] 2024-07-25 09:40
That's a duplicate of #50

**Closed by melegiul** 2024-07-25 09:40 UTC
Labels: enhancement, component/sms, component/enforce-mfa
